"""Domain models — technology-agnostic types for the agent system.

These models do not depend on any framework, database, or SDK.
They define the canonical shapes of agent data.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _new_id() -> str:
    return str(uuid.uuid4())


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class RunStatus(str, Enum):
    QUEUED = "queued"
    RUNNING = "running"
    WAITING = "waiting"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"
    PENDING_APPROVAL = "pending_approval"


class StepStatus(str, Enum):
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


class MessageRole(str, Enum):
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"


class ToolCallStatus(str, Enum):
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    SUCCESS = "success"
    ERROR = "error"
    TIMEOUT = "timeout"
    CANCELLED = "cancelled"


class ArtifactType(str, Enum):
    FILE = "file"
    DIFF = "diff"
    BUILD_OUTPUT = "build_output"
    TEST_OUTPUT = "test_output"
    LOG = "log"
    OTHER = "other"


class MemoryKind(str, Enum):
    WORKING = "working"
    CONVERSATION = "conversation"
    LONG_TERM = "long_term"
    ARTIFACT = "artifact"


# ---------------------------------------------------------------------------
# Domain types
# ---------------------------------------------------------------------------


@dataclass
class Message:
    """A single message in a conversation."""

    role: str  # MessageRole
    content: str
    id: str = field(default_factory=_new_id)
    conversation_id: str = ""
    tool_call_id: str | None = None
    name: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: str = field(default_factory=_now)

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "role": self.role,
            "content": self.content,
            "conversation_id": self.conversation_id,
            "tool_call_id": self.tool_call_id,
            "name": self.name,
            "metadata": self.metadata,
            "created_at": self.created_at,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Message":
        return cls(
            id=data.get("id", _new_id()),
            role=data["role"],
            content=data.get("content", ""),
            conversation_id=data.get("conversation_id", ""),
            tool_call_id=data.get("tool_call_id"),
            name=data.get("name"),
            metadata=data.get("metadata", {}),
            created_at=data.get("created_at", _now()),
        )


@dataclass
class Conversation:
    """A conversation between user and agent."""

    id: str = field(default_factory=_new_id)
    title: str = ""
    workspace_path: str = ""
    messages: list[Message] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: str = field(default_factory=_now)
    updated_at: str = field(default_factory=_now)

    def add_message(self, msg: Message) -> None:
        msg.conversation_id = self.id
        self.messages.append(msg)
        self.updated_at = _now()


@dataclass
class PlanItem:
    """A single step in a plan."""

    description: str
    tools: list[str] = field(default_factory=list)
    files: list[str] = field(default_factory=list)
    expected_output: str = ""
    depends_on: list[str] = field(default_factory=list)
    status: str = StepStatus.PENDING.value


@dataclass
class Plan:
    """A plan generated by the agent."""

    id: str = field(default_factory=_new_id)
    run_id: str = ""
    prompt_version: str = ""
    problem_statement: str = ""
    items: list[PlanItem] = field(default_factory=list)
    constraints: list[str] = field(default_factory=list)
    acceptance_criteria: list[str] = field(default_factory=list)
    risk_class: str = "medium"
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: str = field(default_factory=_now)

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "run_id": self.run_id,
            "prompt_version": self.prompt_version,
            "problem_statement": self.problem_statement,
            "items": [
                {
                    "description": p.description,
                    "tools": p.tools,
                    "files": p.files,
                    "expected_output": p.expected_output,
                    "depends_on": p.depends_on,
                    "status": p.status,
                }
                for p in self.items
            ],
            "constraints": self.constraints,
            "acceptance_criteria": self.acceptance_criteria,
            "risk_class": self.risk_class,
            "metadata": self.metadata,
            "created_at": self.created_at,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Plan":
        items_data = data.get("items") or data.get("finalSteps") or []
        items = [
            PlanItem(
                description=item if isinstance(item, str) else item.get("description", ""),
                status=StepStatus.PENDING.value,
            )
            for item in items_data
        ]
        return cls(
            id=data.get("id", _new_id()),
            run_id=data.get("run_id", ""),
            prompt_version=data.get("prompt_version", ""),
            problem_statement=data.get("problem_statement", ""),
            items=items,
            constraints=data.get("constraints", []),
            acceptance_criteria=data.get("acceptance_criteria", []),
            risk_class=data.get("risk_class", "medium"),
            metadata=data.get("metadata", {}),
            created_at=data.get("created_at", _now()),
        )


@dataclass
class ToolCall:
    """A tool invocation within a run."""

    id: str = field(default_factory=_new_id)
    run_id: str = ""
    step_id: str = ""
    tool_name: str = ""
    input_params: dict[str, Any] = field(default_factory=dict)
    output: Any = None
    error: str | None = None
    status: str = ToolCallStatus.PENDING.value
    duration_ms: float = 0.0
    truncated: bool = False
    idempotency_key: str | None = None
    created_at: str = field(default_factory=_now)
    updated_at: str = field(default_factory=_now)


@dataclass
class ToolResult:
    """Result from a tool call (separate from ToolCall for dedup)."""

    id: str = field(default_factory=_new_id)
    tool_call_id: str = ""
    output: Any = None
    error: str | None = None
    truncated: bool = False
    created_at: str = field(default_factory=_now)


@dataclass
class Artifact:
    """An artifact produced during a run (file, diff, build output, etc.)."""

    id: str = field(default_factory=_new_id)
    run_id: str = ""
    artifact_type: str = ArtifactType.FILE.value
    name: str = ""
    path: str = ""
    checksum: str = ""
    size_bytes: int = 0
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: str = field(default_factory=_now)


@dataclass
class Memory:
    """A unit of long-term or working memory."""

    id: str = field(default_factory=_new_id)
    run_id: str = ""
    kind: str = MemoryKind.WORKING.value
    source: str = ""
    content: str = ""
    tags: list[str] = field(default_factory=list)
    importance: float = 0.5
    activation: float = 0.0
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: str = field(default_factory=_now)
    updated_at: str = field(default_factory=_now)


@dataclass
class ModelUsageRecord:
    """Token usage record for a model call."""

    id: str = field(default_factory=_new_id)
    run_id: str = ""
    step_id: str = ""
    model: str = ""
    input_tokens: int = 0
    output_tokens: int = 0
    cache_creation_input_tokens: int = 0
    cache_read_input_tokens: int = 0
    created_at: str = field(default_factory=_now)

    @property
    def total_tokens(self) -> int:
        return self.input_tokens + self.output_tokens


@dataclass
class AgentStep:
    """A single step in an agent run."""

    id: str = field(default_factory=_new_id)
    run_id: str = ""
    name: str = ""
    role: str = ""
    status: str = StepStatus.PENDING.value
    input_data: dict[str, Any] = field(default_factory=dict)
    output_data: dict[str, Any] = field(default_factory=dict)
    error: str | None = None
    tool_calls: list[ToolCall] = field(default_factory=list)
    usage: list[ModelUsageRecord] = field(default_factory=list)
    duration_ms: float = 0.0
    checkpoint_data: dict[str, Any] = field(default_factory=dict)
    created_at: str = field(default_factory=_now)
    updated_at: str = field(default_factory=_now)


@dataclass
class AgentRun:
    """An agent run representing a complete task execution."""

    id: str = field(default_factory=_new_id)
    conversation_id: str = ""
    session_id: str = ""
    task: str = ""
    status: str = RunStatus.QUEUED.value
    prompt_version: str = ""
    workspace_path: str = ""
    steps: list[AgentStep] = field(default_factory=list)
    plan: Plan | None = None
    messages: list[Message] = field(default_factory=list)
    artifacts: list[Artifact] = field(default_factory=list)
    memories: list[Memory] = field(default_factory=list)
    usage: list[ModelUsageRecord] = field(default_factory=list)
    result: dict[str, Any] = field(default_factory=dict)
    error: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: str = field(default_factory=_now)
    updated_at: str = field(default_factory=_now)
    completed_at: str | None = None

    @property
    def is_terminal(self) -> bool:
        return self.status in {
            RunStatus.COMPLETED.value,
            RunStatus.FAILED.value,
            RunStatus.CANCELLED.value,
        }

    def add_step(self, step: AgentStep) -> None:
        step.run_id = self.id
        self.steps.append(step)
        self.updated_at = _now()

    def add_message(self, msg: Message) -> None:
        self.messages.append(msg)
        self.updated_at = _now()

    def mark_completed(self, result: dict[str, Any] | None = None) -> None:
        self.status = RunStatus.COMPLETED.value
        self.result = result or {}
        self.completed_at = _now()
        self.updated_at = _now()

    def mark_failed(self, error: str) -> None:
        self.status = RunStatus.FAILED.value
        self.error = error
        self.completed_at = _now()
        self.updated_at = _now()

    def mark_cancelled(self) -> None:
        self.status = RunStatus.CANCELLED.value
        self.completed_at = _now()
        self.updated_at = _now()

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "conversation_id": self.conversation_id,
            "session_id": self.session_id,
            "task": self.task,
            "status": self.status,
            "prompt_version": self.prompt_version,
            "workspace_path": self.workspace_path,
            "steps": [s.output_data for s in self.steps],
            "plan": self.plan.to_dict() if self.plan else None,
            "messages": [m.to_dict() for m in self.messages],
            "result": self.result,
            "error": self.error,
            "metadata": self.metadata,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "completed_at": self.completed_at,
        }
